blank_issues_enabled: false
contact_links:
  - name: NEW HORYZON Discord server
    url: https://discord.gg/MskvEhPDQz
    about: For any other questions, suggestions or issues that is not listed below, use the official Discord server.